@extends('layouts.app')
@section('title', $information->exists ? 'Edit Informasi' : 'Tambah Informasi')
@section('content')
    <h1>{{ $information->exists ? 'Edit informasi' : 'Tambah informasi' }}</h1>
    <section class="panel form-panel"><form method="POST" action="{{ $information->exists ? route(auth()->user()->role->value.'.information.update', $information) : route(auth()->user()->role->value.'.information.store') }}" class="school-form" data-validated-form novalidate>
        @csrf @if($information->exists) @method('PUT') @endif
        @php($selectedTeaching = old('teaching_assignment_id', $information->teaching_assignment_id))
        <div><label for="teaching_assignment_id">Kelas dan mata pelajaran</label><select id="teaching_assignment_id" name="teaching_assignment_id" required aria-describedby="teaching_assignment_id-error" @error('teaching_assignment_id') aria-invalid="true" @enderror><option value="">Pilih penugasan</option>@foreach($teachings as $teaching)<option value="{{ $teaching->id }}" @selected(is_scalar($selectedTeaching) && (string)$selectedTeaching === (string)$teaching->id)>@if(auth()->user()->role === \App\Enums\UserRole::Administrator){{ $teaching->teacher->user->name }} — @endif{{ $teaching->classroom->name }} — {{ $teaching->subject->name }}</option>@endforeach</select><p class="field-error" id="teaching_assignment_id-error" role="alert" @if(!$errors->has('teaching_assignment_id')) hidden @endif>{{ $errors->first('teaching_assignment_id') }}</p></div>
        <div><label for="title">Judul</label><input id="title" name="title" value="{{ is_scalar(old('title', $information->title)) ? old('title', $information->title) : '' }}" maxlength="200" required aria-describedby="title-error" @error('title') aria-invalid="true" @enderror><p class="field-error" id="title-error" role="alert" @if(!$errors->has('title')) hidden @endif>{{ $errors->first('title') }}</p></div>
        <div><label for="content">Konten</label><textarea id="content" name="content" rows="10" required aria-describedby="content-error" @error('content') aria-invalid="true" @enderror>{{ is_scalar(old('content', $information->content)) ? old('content', $information->content) : '' }}</textarea><p class="field-error" id="content-error" role="alert" @if(!$errors->has('content')) hidden @endif>{{ $errors->first('content') }}</p></div>
        <div><label for="status">Status</label><select id="status" name="status" required aria-describedby="status-error" @error('status') aria-invalid="true" @enderror>@foreach(\App\Enums\PublicationStatus::cases() as $status)<option value="{{ $status->value }}" @selected(old('status', $information->status->value) === $status->value)>{{ $status->label() }}</option>@endforeach</select><p class="field-error" id="status-error" role="alert" @if(!$errors->has('status')) hidden @endif>{{ $errors->first('status') }}</p></div>
        <div><label for="published_at">Tanggal publikasi (opsional)</label><input id="published_at" name="published_at" type="datetime-local" value="{{ is_scalar(old('published_at', $information->published_at?->format('Y-m-d\TH:i'))) ? old('published_at', $information->published_at?->format('Y-m-d\TH:i')) : '' }}" aria-describedby="published_at-error" @error('published_at') aria-invalid="true" @enderror><p class="field-error" id="published_at-error" role="alert" @if(!$errors->has('published_at')) hidden @endif>{{ $errors->first('published_at') }}</p></div>
        <p class="muted">Jika diterbitkan tanpa tanggal, waktu saat ini digunakan. Publikasi mendatang belum terlihat oleh siswa.</p>
        <button class="button-primary" type="submit">Simpan informasi</button><a href="{{ route(auth()->user()->role->value.'.information.index') }}">Batal</a>
    </form></section>
@endsection
